// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BetterMoveDocumentDataSlicesSlice =
  TbmIndexSlice | TbmGuideSlice | TbmAboutSlice | TbmLandingSlice;

/**
 * Content for The Better Move documents
 */
interface BetterMoveDocumentData {
  /**
   * Slice Zone field in *The Better Move*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: better_move.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BetterMoveDocumentDataSlicesSlice>; /**
   * Meta Title field in *The Better Move*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: better_move.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *The Better Move*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: better_move.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *The Better Move*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: better_move.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * The Better Move document from Prismic
 *
 * - **API ID**: `better_move`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BetterMoveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BetterMoveDocumentData>,
    "better_move",
    Lang
  >;

/**
 * Item in *cfp-c-preview → Images*
 */
export interface CfpCPreviewDocumentDataImagesItem {
  /**
   * Image field in *cfp-c-preview → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-c-preview.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Spread field in *cfp-c-preview → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-c-preview.images[].spread
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  spread: prismic.ImageField<never>;
}

/**
 * Content for cfp-c-preview documents
 */
interface CfpCPreviewDocumentData {
  /**
   * Images field in *cfp-c-preview*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-c-preview.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<CfpCPreviewDocumentDataImagesItem>>;
}

/**
 * cfp-c-preview document from Prismic
 *
 * - **API ID**: `cfp-c-preview`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CfpCPreviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CfpCPreviewDocumentData>,
    "cfp-c-preview",
    Lang
  >;

/**
 * Primary content in *cfp-m-preview → Slice zone → Item → Primary*
 */
export interface CfpMPreviewDocumentDataBodyItemSlicePrimary {
  /**
   * Name field in *cfp-m-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-m-preview.body[].item.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *cfp-m-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-m-preview.body[].item.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Spread field in *cfp-m-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-m-preview.body[].item.primary.spread
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  spread: prismic.ImageField<never>;
}

/**
 * Slice for *cfp-m-preview → Slice zone*
 */
export type CfpMPreviewDocumentDataBodyItemSlice = prismic.Slice<
  "item",
  Simplify<CfpMPreviewDocumentDataBodyItemSlicePrimary>,
  never
>;

type CfpMPreviewDocumentDataBodySlice = CfpMPreviewDocumentDataBodyItemSlice;

/**
 * Content for cfp-m-preview documents
 */
interface CfpMPreviewDocumentData {
  /**
   * Slice zone field in *cfp-m-preview*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-m-preview.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<CfpMPreviewDocumentDataBodySlice>;
}

/**
 * cfp-m-preview document from Prismic
 *
 * - **API ID**: `cfp-m-preview`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CfpMPreviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CfpMPreviewDocumentData>,
    "cfp-m-preview",
    Lang
  >;

/**
 * Item in *cfp-r-preview → Gallery*
 */
export interface CfpRPreviewDocumentDataGalleryItem {
  /**
   * Image field in *cfp-r-preview → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-r-preview.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Spread field in *cfp-r-preview → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-r-preview.gallery[].spread
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  spread: prismic.ImageField<never>;
}

/**
 * Content for cfp-r-preview documents
 */
interface CfpRPreviewDocumentData {
  /**
   * Gallery field in *cfp-r-preview*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-r-preview.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<CfpRPreviewDocumentDataGalleryItem>>;
}

/**
 * cfp-r-preview document from Prismic
 *
 * - **API ID**: `cfp-r-preview`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CfpRPreviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CfpRPreviewDocumentData>,
    "cfp-r-preview",
    Lang
  >;

/**
 * Primary content in *cfp-s-preview → Slice zone → Item → Primary*
 */
export interface CfpSPreviewDocumentDataBodyItemSlicePrimary {
  /**
   * Name field in *cfp-s-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-s-preview.body[].item.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *cfp-s-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-s-preview.body[].item.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Spread field in *cfp-s-preview → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-s-preview.body[].item.primary.spread
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  spread: prismic.ImageField<never>;
}

/**
 * Slice for *cfp-s-preview → Slice zone*
 */
export type CfpSPreviewDocumentDataBodyItemSlice = prismic.Slice<
  "item",
  Simplify<CfpSPreviewDocumentDataBodyItemSlicePrimary>,
  never
>;

type CfpSPreviewDocumentDataBodySlice = CfpSPreviewDocumentDataBodyItemSlice;

/**
 * Content for cfp-s-preview documents
 */
interface CfpSPreviewDocumentData {
  /**
   * Slice zone field in *cfp-s-preview*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cfp-s-preview.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<CfpSPreviewDocumentDataBodySlice>;
}

/**
 * cfp-s-preview document from Prismic
 *
 * - **API ID**: `cfp-s-preview`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CfpSPreviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CfpSPreviewDocumentData>,
    "cfp-s-preview",
    Lang
  >;

/**
 * Primary content in *Features → Slice zone → Item → Primary*
 */
export interface FeaturesDocumentDataBodyItemSlicePrimary {
  /**
   * Name field in *Features → Slice zone → Item → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.body[].item.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Features → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.body[].item.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Spread field in *Features → Slice zone → Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.body[].item.primary.spread
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  spread: prismic.ImageField<never>;
}

/**
 * Slice for *Features → Slice zone*
 */
export type FeaturesDocumentDataBodyItemSlice = prismic.Slice<
  "item",
  Simplify<FeaturesDocumentDataBodyItemSlicePrimary>,
  never
>;

type FeaturesDocumentDataBodySlice = FeaturesDocumentDataBodyItemSlice;

/**
 * Content for Features documents
 */
interface FeaturesDocumentData {
  /**
   * Slice zone field in *Features*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: features.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<FeaturesDocumentDataBodySlice>;
}

/**
 * Features document from Prismic
 *
 * - **API ID**: `features`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FeaturesDocumentData>,
    "features",
    Lang
  >;

/**
 * Item in *Gallery → Gallery*
 */
export interface GalleryDocumentDataGalleryItem {
  /**
   * Image field in *Gallery → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Gallery documents
 */
interface GalleryDocumentData {
  /**
   * Gallery field in *Gallery*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<GalleryDocumentDataGalleryItem>>;
}

/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;

/**
 * Item in *Nightlife for all → Recommendations*
 */
export interface NightlifeForAllDocumentDataRecommendationsItem {
  /**
   * Title field in *Nightlife for all → Recommendations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.recommendations[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Nightlife for all → Recommendations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.recommendations[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Nightlife for all → Previews*
 */
export interface NightlifeForAllDocumentDataPreviewsItem {
  /**
   * Cover field in *Nightlife for all → Previews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.previews[].cover
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>;
}

/**
 * Content for Nightlife for all documents
 */
interface NightlifeForAllDocumentData {
  /**
   * Landing Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.landing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  landing: prismic.ImageField<never>;

  /**
   * Summary Text field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.summary_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary_text: prismic.RichTextField;

  /**
   * Summary Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.summary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  summary_image: prismic.ImageField<never>;

  /**
   * Introduction field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * Belonging Quote field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.belonging_quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  belonging_quote: prismic.RichTextField;

  /**
   * Belonging Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.belonging_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  belonging_image: prismic.ImageField<never>;

  /**
   * Belonging Text field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.belonging_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  belonging_text: prismic.RichTextField;

  /**
   * Space Text field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.space_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  space_text: prismic.RichTextField;

  /**
   * Space Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.space_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  space_image: prismic.ImageField<never>;

  /**
   * City Quote field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.city_quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  city_quote: prismic.RichTextField;

  /**
   * City Text field in *Nightlife for all*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.city_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  city_text: prismic.RichTextField;

  /**
   * City Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.city_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  city_image: prismic.ImageField<never>;

  /**
   * Recommendations field in *Nightlife for all*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.recommendations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  recommendations: prismic.GroupField<
    Simplify<NightlifeForAllDocumentDataRecommendationsItem>
  >;

  /**
   * Previews field in *Nightlife for all*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.previews[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  previews: prismic.GroupField<
    Simplify<NightlifeForAllDocumentDataPreviewsItem>
  >;

  /**
   * Quote Image field in *Nightlife for all*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nightlife_for_all.quote_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  quote_image: prismic.ImageField<never>;
}

/**
 * Nightlife for all document from Prismic
 *
 * - **API ID**: `nightlife_for_all`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NightlifeForAllDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NightlifeForAllDocumentData>,
    "nightlife_for_all",
    Lang
  >;

/**
 * Item in *NTER → Recommendations*
 */
export interface NterDocumentDataRecommendationsItem {
  /**
   * Title field in *NTER → Recommendations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.recommendations[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *NTER → Recommendations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.recommendations[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *NTER → Previews*
 */
export interface NterDocumentDataPreviewsItem {
  /**
   * Cover field in *NTER → Previews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.previews[].cover
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>;
}

/**
 * Content for NTER documents
 */
interface NterDocumentData {
  /**
   * Landing Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.landing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  landing: prismic.ImageField<never>;

  /**
   * Summary Text field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.summary_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary_text: prismic.RichTextField;

  /**
   * Summary Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.summary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  summary_image: prismic.ImageField<never>;

  /**
   * Introduction field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * Belonging Quote field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.belonging_quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  belonging_quote: prismic.RichTextField;

  /**
   * Belonging Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.belonging_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  belonging_image: prismic.ImageField<never>;

  /**
   * Belonging Text field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.belonging_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  belonging_text: prismic.RichTextField;

  /**
   * Space Text field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.space_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  space_text: prismic.RichTextField;

  /**
   * Space Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.space_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  space_image: prismic.ImageField<never>;

  /**
   * City Quote field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.city_quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  city_quote: prismic.RichTextField;

  /**
   * City Text field in *NTER*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.city_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  city_text: prismic.RichTextField;

  /**
   * City Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.city_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  city_image: prismic.ImageField<never>;

  /**
   * Recommendations field in *NTER*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.recommendations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  recommendations: prismic.GroupField<
    Simplify<NterDocumentDataRecommendationsItem>
  >;

  /**
   * Previews field in *NTER*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.previews[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  previews: prismic.GroupField<Simplify<NterDocumentDataPreviewsItem>>;

  /**
   * Quote Image field in *NTER*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nter.quote_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  quote_image: prismic.ImageField<never>;
}

/**
 * NTER document from Prismic
 *
 * - **API ID**: `nter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NterDocumentData>, "nter", Lang>;

export type AllDocumentTypes =
  | BetterMoveDocument
  | CfpCPreviewDocument
  | CfpMPreviewDocument
  | CfpRPreviewDocument
  | CfpSPreviewDocument
  | FeaturesDocument
  | GalleryDocument
  | NightlifeForAllDocument
  | NterDocument;

/**
 * Primary content in *TbmAbout → Default → Primary*
 */
export interface TbmAboutSliceDefaultPrimary {
  /**
   * Title field in *TbmAbout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *TbmAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_about.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *TbmAbout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TbmAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TbmAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TbmAbout*
 */
type TbmAboutSliceVariation = TbmAboutSliceDefault;

/**
 * TbmAbout Shared Slice
 *
 * - **API ID**: `tbm_about`
 * - **Description**: TbmAbout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmAboutSlice = prismic.SharedSlice<
  "tbm_about",
  TbmAboutSliceVariation
>;

/**
 * Primary content in *TbmGuide → Default → Primary*
 */
export interface TbmGuideSliceDefaultPrimary {
  /**
   * Body field in *TbmGuide → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_guide.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Download text field in *TbmGuide → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_guide.default.primary.download_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  download_text: prismic.RichTextField;

  /**
   * Download link field in *TbmGuide → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_guide.default.primary.download_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  download_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for TbmGuide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmGuideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TbmGuideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TbmGuide*
 */
type TbmGuideSliceVariation = TbmGuideSliceDefault;

/**
 * TbmGuide Shared Slice
 *
 * - **API ID**: `tbm_guide`
 * - **Description**: TbmGuide
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmGuideSlice = prismic.SharedSlice<
  "tbm_guide",
  TbmGuideSliceVariation
>;

/**
 * Primary content in *TbmIndex → Default → Primary*
 */
export interface TbmIndexSliceDefaultPrimary {
  /**
   * Column One Body field in *TbmIndex → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_index.default.primary.column_one_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  column_one_body: prismic.RichTextField;

  /**
   * Column Two Body field in *TbmIndex → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_index.default.primary.column_two_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  column_two_body: prismic.RichTextField;
}

/**
 * Default variation for TbmIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TbmIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TbmIndex*
 */
type TbmIndexSliceVariation = TbmIndexSliceDefault;

/**
 * TbmIndex Shared Slice
 *
 * - **API ID**: `tbm_index`
 * - **Description**: TbmIndex
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmIndexSlice = prismic.SharedSlice<
  "tbm_index",
  TbmIndexSliceVariation
>;

/**
 * Primary content in *TbmLanding → Default → Primary*
 */
export interface TbmLandingSliceDefaultPrimary {
  /**
   * Subtitle field in *TbmLanding → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tbm_landing.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for TbmLanding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmLandingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TbmLandingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TbmLanding*
 */
type TbmLandingSliceVariation = TbmLandingSliceDefault;

/**
 * TbmLanding Shared Slice
 *
 * - **API ID**: `tbm_landing`
 * - **Description**: TbmLanding
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TbmLandingSlice = prismic.SharedSlice<
  "tbm_landing",
  TbmLandingSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BetterMoveDocument,
      BetterMoveDocumentData,
      BetterMoveDocumentDataSlicesSlice,
      CfpCPreviewDocument,
      CfpCPreviewDocumentData,
      CfpCPreviewDocumentDataImagesItem,
      CfpMPreviewDocument,
      CfpMPreviewDocumentData,
      CfpMPreviewDocumentDataBodyItemSlicePrimary,
      CfpMPreviewDocumentDataBodySlice,
      CfpRPreviewDocument,
      CfpRPreviewDocumentData,
      CfpRPreviewDocumentDataGalleryItem,
      CfpSPreviewDocument,
      CfpSPreviewDocumentData,
      CfpSPreviewDocumentDataBodyItemSlicePrimary,
      CfpSPreviewDocumentDataBodySlice,
      FeaturesDocument,
      FeaturesDocumentData,
      FeaturesDocumentDataBodyItemSlicePrimary,
      FeaturesDocumentDataBodySlice,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataGalleryItem,
      NightlifeForAllDocument,
      NightlifeForAllDocumentData,
      NightlifeForAllDocumentDataRecommendationsItem,
      NightlifeForAllDocumentDataPreviewsItem,
      NterDocument,
      NterDocumentData,
      NterDocumentDataRecommendationsItem,
      NterDocumentDataPreviewsItem,
      AllDocumentTypes,
      TbmAboutSlice,
      TbmAboutSliceDefaultPrimary,
      TbmAboutSliceVariation,
      TbmAboutSliceDefault,
      TbmGuideSlice,
      TbmGuideSliceDefaultPrimary,
      TbmGuideSliceVariation,
      TbmGuideSliceDefault,
      TbmIndexSlice,
      TbmIndexSliceDefaultPrimary,
      TbmIndexSliceVariation,
      TbmIndexSliceDefault,
      TbmLandingSlice,
      TbmLandingSliceDefaultPrimary,
      TbmLandingSliceVariation,
      TbmLandingSliceDefault,
    };
  }
}
