// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  tbm_about: defineAsyncComponent(() => import("./TbmAbout/index.vue")),
  tbm_guide: defineAsyncComponent(() => import("./TbmGuide/index.vue")),
  tbm_index: defineAsyncComponent(() => import("./TbmIndex/index.vue")),
  tbm_landing: defineAsyncComponent(() => import("./TbmLanding/index.vue")),
});
